# -*- coding: utf-8 -*-
"""YASH  (Data Analysis (Hotel Booking).ipynb)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWCMChIRqZVa7B23VBf40sU5Tkgi1x-o

Research Question
1. What are the variables that affect hotel reservation cancelleations?
2. How can we make hotel reservations cancellations better?
3. How will hotels be assisted in making pricing and promotional decesions?

### Hypothesis

1.More cancellations occur when prices are higher.
2.When there is a longer waiting list,coustomer tend to cancel more frequently.
3.The marjority of clients are comiong from offline travel agents to make their reservations.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""### Loading the dataset"""

df=pd.read_csv('hotel_booking.csv')

"""### Exploratory Data Analysis and Data Cleaning"""

df.head()

# rows and column
df.shape

df.columns

df.info()

df['reservation_status_date']=pd.to_datetime(df['reservation_status_date'])

df.describe(include='object')

for col in df.describe(include='object').columns:
    print(col)
    print(df[col].unique())
    print('-'*50)

df.isnull().sum()

df.drop(['company','agent','name','email','credit_card','phone-number'],axis=1,inplace=True)
df.dropna(inplace=True)

df.isnull().sum()

df.describe(include ='object')

for col in df.describe(include='object').columns:
    print(col)
    print(df[col].unique())
    print('-'*50)

df.isnull().sum()

df.describe()

df=df[df['adr']<5000]

"""### Data Analysis and Visualizations"""

cancelled_perc = df['is_canceled'].value_counts(normalize=True)
print(cancelled_perc)

plt.figure(figsize=(5,4))
plt.title('Reservation status count')
plt.bar(['Not canceled','Canceled'],df['is_canceled'].value_counts(),edgecolor = 'k',width=0.7)
plt.show()

"""The accompanying bar graph shows the percentage of reservations that are canceled and those that are not. it is as obvious that are still significant number of reservations that have not been canceled. These are still 37% of clients who canceled their reservation, Which has a significant impact on the hotels earning"""

plt.figure(figsize=(8,4))
ax1=sns.countplot(x='hotel',hue='is_canceled',data=df,palette='Blues')
legend_labels=ax1.get_legend_handles_labels()
plt.title('Reservation status in different hotels',size=20)
plt.xlabel('hotel')
plt.ylabel('number of reservation')
plt.legend(['not_canceled','canceled'])
plt.show()

"""In comparision to resort hotels,city hotels have more bookings.It's possible that resort hotels are more expensive than those in cities."""

resort_hotel=df[df['hotel']=='Resort Hotel']
resort_hotel['is_canceled'].value_counts(normalize=True)

city_hotel=df[df['hotel']=='City Hotel']
city_hotel['is_canceled'].value_counts(normalize=True)

resort_hotel = resort_hotel.groupby('reservation_status_date')[['adr']].mean()
city_hotel = city_hotel.groupby('reservation_status_date')[['adr']].mean()

plt.figure(figsize=(20,8))
plt.title('Average Daily Rate in City and Resort Hotel',fontsize=30)
plt.plot(resort_hotel.index, resort_hotel['adr'],label='Resort Hotel')
plt.plot(city_hotel.index, city_hotel['adr'],label='City Hotel')
plt.legend(fontsize=20)
plt.show()

"""The line graph above shows that on certain days,the average daily rate for a city hotel is less than that of a
resort hotel,and on other days,it is even less. It goes without saying that weekends and holiday may see a rise in resort hotel rates.
"""

df['month']=df['reservation_status_date'].dt.month
plt.figure(figsize=(16,8))
ax1=sns.countplot(x='month',hue='is_canceled',data=df,palette='bright')
legend_labels,_ = ax1.get_legend_handles_labels()
ax1.legend(bbox_to_anchor=(1,1))
plt.title('Reservation status per month',size=20)
plt.xlabel('month')
plt.ylabel('number of reservations')
plt.legend(['not_canceled','canceled'])
plt.show()

"""we have developed the grouped bar to analyze the months with the highest and
lowest reservation levels according to reservation status. As can be seen, both the
number of confirmed reservations and the number of canceled reservations are largest
in the month of August.Whereas January is the month with the most canceled reservations.
"""

plt.figure(figsize=(15,8))
plt.title('ADR per month',fontsize=30)
sns.barplot('month','adr',data=df[df['is_canceled']==1].groupby('month')[['adr']].sum().reset_index())
plt.show()

"""This bar graph demonstrates that cancellations are most common when proces are
greatest and arre least common when they are lowest.Therefore,the cost of the
accommodation is soley responsible for the cancellation.

Now,lets see Which country has the highest reservation canceled.The top
country is Portugal with highest number if cancellations.
"""

cancelled_data= df[df['is_canceled']==1]
top_10_country = cancelled_data['country'].value_counts()[:10]
plt.figure(figsize=(8,8))
plt.title('Top 10 countries with reservation canceled')
plt.pie(top_10_country,autopct='%.2f',labels = top_10_country.index)
plt.show()

"""Lets check the area from where guests are visiting the hotels and making reservations.Is it coming from Direct or Groups, Online or Offline Travel Agents? Areoubd 46% of the clients come from online travel agencies,Whereas 27% come from groups.Only 4% of clients book hotels directly by visiting them
making reservations.
"""

df['market_segment'].value_counts()

df['market_segment'].value_counts(normalize=True)

cancelled_data['market_segment'].value_counts(normalize=True)

cancelled_df_adr = cancelled_data.groupby('reservation_status_date')[['adr']].mean()
cancelled_df_adr.reset_index(inplace=True)
cancelled_df_adr.sort_values('reservation_status_date',inplace = True)

not_cancelled_data = df[df['is_canceled']==0]
not_cancelled_df_adr = not_cancelled_data.groupby('reservation_status_date')[['adr']].mean()
not_cancelled_df_adr.reset_index(inplace=True)
not_cancelled_df_adr.sort_values('reservation_status_date',inplace = True)

plt.figure(figsize=(20,6))
plt.title('Average Daily Rate')
plt.plot(not_cancelled_df_adr['reservation_status_date'],not_cancelled_df_adr['adr'],label ='not cancelled')
plt.plot(cancelled_df_adr['reservation_status_date'],cancelled_df_adr['adr'],label ='cancelled')
plt.legend()

cancelled_df_adr=cancelled_df_adr[(cancelled_df_adr['reservation_status_date']>'2016') & (cancelled_df_adr['reservation_status_date']<'2017-09')]
not_cancelled_df_adr=not_cancelled_df_adr[(not_cancelled_df_adr['reservation_status_date']>'2016') & (not_cancelled_df_adr['reservation_status_date']<'2017-09')]

plt.figure(figsize=(20,6))
plt.title('Average Daily Rate')
plt.plot(not_cancelled_df_adr['reservation_status_date'],not_cancelled_df_adr['adr'],label ='not cancelled')
plt.plot(cancelled_df_adr['reservation_status_date'],cancelled_df_adr['adr'],label ='cancelled')
plt.legend(fontsize=20)

"""As seen in the graph, reservations are canceled when the average daily rate is higher
than When it is not canceled.It clearly proves all the above analysis, that the higher
price leads to higher cancellation

### suggestions

1. Cancellation rates rise as the price does.In order to prevent cancellations of
reservations, hotels could work on their pricing stratergies and try to lower the
rates for specific hotels based on locations. They can also provide some discounts
to the coustomers.

2. As the ratio the cancellation and not cancellation of the resort hotel is higher in
the resort hotel than the city hotels.So the hotels should provide a resonable
discount on the room prices on weekends or holidays.

3. In the month of Januaury, hotels can start campaigans or marketing with a
reasnable amount to increase their revenue as the calculations is the highest
in this month

4. They can also increase the quality of their hotels and their sercvices manily
in Portugal to reduce the cancellation rate.
"""

